SET FOREIGN_KEY_CHECKS = 0;
drop table if exists bruker;
drop table if exists brukertype;
drop table if exists fase;
drop table if exists forslag_tidsestimat;
drop table if exists oppgave;
drop table if exists oppgavetype;
drop table if exists prosjekt;
drop table if exists team;
drop table if exists teammedlemskap;
drop table if exists timeregistrering;
SET FOREIGN_KEY_CHECKS = 1;